default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: challenge_omthirty
  username: postgres
  password: postgres
  host: db
  port: 5432
  
test:
  <<: *default
  database: challenge_omthirty
  username: postgres
  password: postgres
  host: db
  port: 5432

production:
  <<: *default
  database: challenge_omthirty
  username: postgres
  password: postgres